image:
  file: .gitpod.dockerfile
ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- init: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  command: cp -r /workspace/elnw/.jupyter /home/gitpod/

vscode:
  extensions:
    - efoerster.texlab@2.2.1:58163fe2a360fec2e5f6b24c6e34a5af
    - james-yu.latex-workshop@8.18.0:765947dfaa1d20a4162c9b5778bc1c30
