image:
  file: .gitpod.dockerfile
ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- init: echo hi
  command: cp -r /workspace/dash-and-jupyter-notebook-with-gitpod/.jupyter /home/gitpod/

vscode:
  extensions:
    - efoerster.texlab@2.2.1:58163fe2a360fec2e5f6b24c6e34a5af
    - james-yu.latex-workshop@8.18.0:765947dfaa1d20a4162c9b5778bc1c30