ELNW_PR_Juan4.tex.pdf: ELNW_PR_Juan4.sagetex.sout
	pdflatex -interaction=nonstopmode --shell-escape ELNW_PR_Juan4.tex
ELNW_PR_Juan4.sagetex.sout: ELNW_PR_Juan4.sagetex.sage
	sage ELNW_PR_Juan4.sagetex.sage
ELNW_PR_Juan4.sagetex.sage:
	pdflatex -interaction=nonstopmode --shell-escape ELNW_PR_Juan4.tex