ELNW_PR_Juan5.tex.pdf: #ELNW_PR_Juan5.sagetex.sout
	pdflatex -interaction=nonstopmode --shell-escape ELNW_PR_Juan5.tex
ELNW_PR_Juan5.sagetex.sout: ELNW_PR_Juan5.sagetex.sage
	sage ELNW_PR_Juan5.sagetex.sage
ELNW_PR_Juan5.sagetex.sage:
	pdflatex -interaction=nonstopmode --shell-escape ELNW_PR_Juan5.tex